### ISSUE TITLE
Update of boolean Lead's fields

### ISSUE THREAD

**Issue by FrancescJR** [mautic/api-library#23]
How can I set a boolean field to False?

I am trying many combinations but with no luck so far:
1.
`$data = array('boolean_sample' => 0); //value in lead is still 1..`
2.
`$data = array('boolean_sample' => FALSE); //field is still set to 1 like above`
3.
`$data = array('boolean_sample' => 'FALSE'); //returns empty array as if nothing was updated`

How should I do?

**Comment by escopecz** [comment]
Just tested this scenario with the API Tester and it worked. The previous value was `NULL`.
![mautic-boolean](https://cloud.githubusercontent.com/assets/1235442/12945739/bc7bbf2a-cfef-11e5-8b26-13720be12b98.png)

**Comment by FrancescJR** [comment]
Oh sorry or the late reply.

Ok I will take a look again, but I forgot to mention that I could actually set a boolean to true, but once it is true, I could not set it back to false.

**Comment by FrancescJR** [comment]
Yes the problem is that I am unable to set a boolean back to false, once its value is true, which value should I put to make it false again? 0, false, 'false' didn't work.

Thanks for taking a look at this!

**Comment by escopecz** [comment]
I can replicate

**Comment by escopecz** [comment]
Update: Should be fixed in the upcoming Mautic 2.2.0

**Comment by trops** [comment]
Im still unable to update the boolean fields using the API. I am using 1 or 0 as the values and nothing is changing in the contact custom fields that I have set up.

**Comment by escopecz** [comment]
Working with Mautic 2.6.1

**Comment by termax** [comment]
Mautic 2.8.2 very strange:
I can set it to 1 in the web gui ... but in API i can only set it to false or 0
Seting it to one or true doesn't do anything

**Comment by termax** [comment]
figured it out was not properly setting the params but still strange why that reset my custom Boolean param to 0 all the time
